yarn add v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ nouislider@15.7.1
info All dependencies
└─ nouislider@15.7.1
Done in 26.06s.
